language: ruby
dist: xenial
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head

cache: bundler
bundler_args: --jobs=2

script:
  - bundle exec rake spec
